# version 1.0.0
# LightLoginPlugin
#--------------------

language: 'ENGLISH' # "ENGLISH", "CHINESE", "RUSSIAN", "FRENCH", "HEBREW", "ITALIAN", "SPANISH", "FILIPINO"
                    # 更改以设置您的语言
                    # Измените, чтобы установить ваш язык
                    # שנה כדי להגדיר את השפה של
                    # Changez pour définir votre langue
                    # Cambia per impostare la tua lingua
                    # Cambiar para establecer tu idioma
