name: 'LightLogin'
main: 'top.cmarco.lightlogin.LightLoginPlugin'
version: ${project.version}
load: 'STARTUP'
api-version: '1.16'
author: 'CMarco'
authors: ['mfnalex']
database: false
description: 'Optimised and Safe SpigotMC Software for Authentication'
libraries:
  - 'org.bouncycastle:bcpkix-jdk18on:1.77'
  - 'com.zaxxer:HikariCP:5.1.0'
commands:
  login:
    description: 'Login into the server.'
  register:
    description: 'Register into the server.'
  unregister:
    description: 'Unregister a user from the server.'