name: "LightLogin"
main: "top.cmarco.lightlogin.LightLoginPlugin"
version: ${project.version}
load: 'POSTWORLD'
folia-support: false
api-version: "1.17"
author: "CMarco"
database: false
description: "Optimised and Safe SpigotMC Software for Authentication"
commands:
  login:
    description: "Login into the server."
  register:
    description: "Register into the server."
  unregister:
    description: "Unregister a user from the server."
  lightlogin:
    description: "Information about this software"
  changepassword:
    description: "Change your current password."
  unlogin:
    description: "Remove login session from a player."