name: 'LightLogin'
main: 'top.cmarco.lightlogin.LightLoginPlugin'
version: 1.0.0-SNAPSHOT
load: 'STARTUP'
api-version: '1.13'
author: 'CMarco'
database: false
description: 'Optimised and Safe SpigotMC Software for Authentication'
libraries:
  - 'org.bouncycastle:bcpkix-jdk18on:1.77'
